%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/cyano/Documents/GitHub/SCUID-APL/MFC_Tests/MFC_Test_Data/NO_Tests/2022-09-02_Humidity/2022lvtemporary_63780.tmp.csv
%
% Auto-generated by MATLAB on 06-Sep-2022 12:19:39

clear; close all; clc;

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 26, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["TimeKeithley1", "ResistanceOhmsKeithley1", "TimeKeithley2", "ResistanceOhmsKeithley2", "TimeKeithley3", "ResistanceOhmsKeithley3", "TimeKeithley4", "ResistanceOhmsKeithley4", "TimeKeithley5", "ResistanceOhmsKeithley5", "TimeKeithley6", "ResistanceOhmsKeithley6", "TimeKeithley7", "ResistanceOhmsKeithley7", "TimeKeithley8", "ResistanceOhmsKeithley8", "TimeKeithley9", "ResistanceOhmsKeithley9", "TimeKeithley10", "ResistanceOhmsKeithley10", "TimeKeithley11", "ResistanceOhmsKeithley11", "TimeKeithley12", "ResistanceOhmsKeithley12", "TimeMFC0Flow", "FlowccmMFC0Flow"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
data = readtable("/Users/cyano/Documents/GitHub/SCUID-APL/MFC_Tests/MFC_Test_Data/NO_Tests/2022-09-02_Humidity/2022lvtemporary_63780.tmp.csv", opts);


%% Clear temporary variables
clear opts

f = figure();
f.Position = [200,200,1400,600];
tiledlayout(1,1)
ax = nexttile;
hold(ax,"on");

plot(ax, data.TimeKeithley7(1:43000), data.ResistanceOhmsKeithley7(1:43000)/data.ResistanceOhmsKeithley7(1200),LineWidth=2)
plot(ax, data.TimeKeithley8(1:43000), data.ResistanceOhmsKeithley8(1:43000)/data.ResistanceOhmsKeithley8(1200),LineWidth=2)
plot(ax, data.TimeKeithley9(1:43000), data.ResistanceOhmsKeithley9(1:43000)/data.ResistanceOhmsKeithley9(1200),LineWidth=2)
plot(ax, data.TimeKeithley10(1:43000), data.ResistanceOhmsKeithley10(1:43000)/data.ResistanceOhmsKeithley10(1200),LineWidth=2)
plot(ax, data.TimeKeithley11(1:43000), data.ResistanceOhmsKeithley11(1:43000)/data.ResistanceOhmsKeithley11(1200),LineWidth=2)
plot(ax, data.TimeKeithley12(1:43000), data.ResistanceOhmsKeithley12(1:43000)/data.ResistanceOhmsKeithley12(1200),LineWidth=2)
legend(ax, ["Pad 7","Pad 8","Pad 9","Pad 10","Pad 11","Pad 12"])
xlabel("Keithley Time")
ylabel("R/R_0")
%% Overall Plot Format Settings
all_figs = findall(groot,'type','figure');
all_axes = findall(all_figs,'type','axes');
set(all_axes,'FontSize',20, 'box','off')
all_lgds = findall(all_figs,'type','legend');
set(all_lgds,'edgecolor','none', 'location','northeast');